name: nailo
description: "Aplicativo de controle de agenda para esmalteria."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

  # --------------------------
  # ğŸ”¥ FIREBASE
  # --------------------------
  firebase_core: ^3.4.0
  firebase_auth: ^5.3.1
  cloud_firestore: ^5.4.0
  firebase_storage: ^12.2.0
  firebase_messaging: ^15.1.3

  # --------------------------
  # âš™ï¸ FUNCIONALIDADES EXTRAS
  # --------------------------
  flutter_local_notifications: ^17.1.2
  http: ^1.2.2
  intl: ^0.19.0
  get: ^4.6.6
  image_picker: ^1.1.2
  permission_handler: ^11.3.1
  shared_preferences: ^2.3.2
  flutter_animate: ^4.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
